/**
 * Agent 3: Content Writer
 * Transforms raw intelligence and research into post-ready content
 */

import { log } from '../log';
import { llmService } from '../services/llmService';
import { ContentVariationEngine } from '../content/variation';
import { PostDraft } from '../types';
import crypto from 'crypto';
import fs from 'fs';
import yaml from 'yaml';

interface ContentToGenerate {
  intelligence: any;
  research?: any;
}

export class ContentWriterAgent {
  private variationEngine: ContentVariationEngine;
  private config: any;
  
  constructor() {
    this.variationEngine = new ContentVariationEngine();
    this.loadConfig();
  }
  
  private loadConfig() {
    try {
      const configPath = './config/agent-config.yaml';
      const configFile = fs.readFileSync(configPath, 'utf8');
      const fullConfig = yaml.parse(configFile);
      this.config = fullConfig.content_writer || {
        generation_mode: 'hybrid',
        auto_posts: { enabled: true, target_count: 20 },
        premium_posts: { enabled: true, target_count: 10 }
      };
      
      log.info({
        mode: this.config.generation_mode,
        autoCount: this.config.auto_posts?.target_count,
        premiumCount: this.config.premium_posts?.target_count
      }, '[Agent 3] Loaded config');
    } catch (error) {
      log.error({ error: (error as Error).message }, '[Agent 3] Failed to load config');
      this.config = { generation_mode: 'rule_based' };
    }
  }
  
  /**
   * Main agent execution
   */
  async run(): Promise<{ items_processed: number; items_created: number; items_failed: number }> {
    log.info('[Agent 3] Starting content writer...');
    
    try {
      // 1. Get processed intelligence + research
      const intelligence = await this.getProcessedIntelligence();
      const research = await this.getUnusedResearch();
      
      log.info({
        intelligence: intelligence.length,
        research: research.length
      }, '[Agent 3] Retrieved data for content generation');
      
      // 2. Generate content from each source
      const generatedContent: any[] = [];
      let failedCount = 0;
      
      // Determine how many auto vs premium to generate
      const autoTarget = this.config.auto_posts?.target_count || 20;
      const premiumTarget = this.config.premium_posts?.target_count || 10;
      
      let autoGenerated = 0;
      let premiumGenerated = 0;
      
      // Generate from intelligence
      for (const item of intelligence) {
        if (autoGenerated >= autoTarget && premiumGenerated >= premiumTarget) {
          break;  // Hit both targets
        }
        
        try {
          // Find related research
          const relatedResearch = this.findRelatedResearch(item, research);
          
          // Decide if this should be premium or auto
          const isPremium = premiumGenerated < premiumTarget;
          
          if (isPremium) {
            // Generate premium posts with LLM (5 variations, pick best)
            log.info({ item: item.id }, '[Agent 3] Generating PREMIUM content with GPT-4o');
            
            for (let i = 0; i < 5; i++) {
              const content = await this.generateContent(item, relatedResearch, i, 'premium');
              
              if (content) {
                await this.storeInQueue(content);
                generatedContent.push(content);
              }
            }
            
            premiumGenerated++;
            
          } else if (autoGenerated < autoTarget) {
            // Generate auto posts with templates (3 variations)
            log.info({ item: item.id }, '[Agent 3] Generating AUTO content (rule-based)');
            
            for (let i = 0; i < 3; i++) {
              const content = await this.generateContent(item, relatedResearch, i, 'auto');
              
              if (content) {
                await this.storeInQueue(content);
                generatedContent.push(content);
              }
            }
            
            autoGenerated++;
          }
          
        } catch (error) {
          log.error({
            item: item.id,
            error: (error as Error).message
          }, '[Agent 3] Failed to generate content');
          failedCount++;
        }
      }
      
      log.info({
        autoGenerated,
        premiumGenerated,
        total: generatedContent.length
      }, '[Agent 3] Content generation split complete');
      
      // 3. Mark intelligence as processed by writer
      if (intelligence.length > 0) {
        await this.markAsProcessedByWriter(
          intelligence.map((i: any) => i.id)
        );
      }
      
      log.info({
        processed: intelligence.length,
        generated: generatedContent.length,
        failed: failedCount
      }, '[Agent 3] Content writer complete');
      
      return {
        items_processed: intelligence.length,
        items_created: generatedContent.length,
        items_failed: failedCount
      };
      
    } catch (error) {
      log.error({ error: (error as Error).message }, '[Agent 3] Critical error');
      throw error;
    }
  }
  
  /**
   * Generate content from intelligence and research (HYBRID MODE)
   */
  private async generateContent(
    intelligence: any,
    research: any | null,
    variationNumber: number,
    tier: 'premium' | 'auto' = 'auto'
  ): Promise<any | null> {
    try {
      // Determine content type
      const contentType = intelligence.source_type === 'twitter_scrape' ? 'commentary' : 'news';
      
      // Generate base post
      let text = '';
      
      if (tier === 'premium' && this.config.premium_posts?.use_llm) {
        // PREMIUM: Use LLM for highest quality
        log.info({ tier: 'premium', contentType }, '[Agent 3] Using GPT-4o for premium content');
        
        try {
          const sourceType = contentType === 'commentary' ? 'twitter' : 'rss';
          text = await llmService.generatePremiumContent(intelligence, research, sourceType);
          
          // Add source URL if not already included
          if (!text.includes('http') && intelligence.source_url) {
            text += `\n\n${intelligence.source_url}`;
          }
        } catch (error) {
          log.warn({ error: (error as Error).message }, '[Agent 3] LLM generation failed, falling back to templates');
          text = this.generateCommentary(intelligence.raw_content, intelligence.source_account, research);
        }
        
      } else {
        // AUTO: Use rule-based templates
        if (contentType === 'commentary') {
          text = this.generateCommentary(intelligence.raw_content, intelligence.source_account, research);
        } else {
          text = `${intelligence.title}\n\n${intelligence.summary}\n\n${intelligence.source_url}`;
        }
      }
      
      // Ensure fits in 280 characters
      if (text.length > 277) {
        text = text.substring(0, 274) + '...';
      }
      
      // Create draft
      const contentHash = crypto.createHash('sha256').update(text).digest('hex').slice(0, 16);
      
      let draft: PostDraft = {
        text,
        sourceUrl: intelligence.source_url,
        contentHash,
        confidence: intelligence.metadata?.score || intelligence.metadata?.weight || 0.7
      };
      
      // Apply variation if not first variation (for auto posts only)
      if (variationNumber > 0 && tier === 'auto') {
        draft = this.variationEngine.addContentVariation(draft, variationNumber);
      }
      
      return {
        source_intelligence_ids: [intelligence.id],
        source_research_ids: research ? [research.id] : [],
        content_text: draft.text,
        content_hash: draft.contentHash,
        content_type: contentType,
        topic_tags: intelligence.metadata?.tags || [intelligence.metadata?.category] || [],
        quality_score: tier === 'premium' ? 0.9 : 0.7,  // Premium gets higher initial score
        confidence_score: draft.confidence || 0.7,
        variation_number: variationNumber + 1,
        status: tier === 'premium' ? 'pending_manual_review' : 'pending_approval',  // Premium requires review
        created_by_agent: tier === 'premium' ? 'content_writer_premium' : 'content_writer_auto',
        metadata: { tier, llm_generated: tier === 'premium' }
      };
      
    } catch (error) {
      log.error({ error: (error as Error).message }, '[Agent 3] Failed to generate content');
      return null;
    }
  }
  
  /**
   * Generate commentary on a scraped post
   */
  private generateCommentary(original: string, author: string | undefined, research: any): string {
    // Simple commentary generation
    // TODO: Enhance with GPT/Claude for better quality
    
    const authorName = author || 'this account';
    
    const commentaryTypes = [
      `Interesting take from ${authorName}. ${research ? 'Research shows' : 'Worth noting'} this aligns with recent developments.`,
      `${authorName} raises good points here. The implications for DeFi are significant.`,
      `This ${authorName} thread is worth reading. Key insights on the current state of Ethereum.`,
      `Solid analysis from ${authorName}. The technical depth here is impressive.`
    ];
    
    const index = Math.floor(Math.random() * commentaryTypes.length);
    const commentary: string = commentaryTypes[index]!;
    
    return commentary;
  }
  
  /**
   * Find related research for an intelligence item
   */
  private findRelatedResearch(intelligence: any, research: any[]): any | null {
    if (!research || research.length === 0) return null;
    
    // Simple matching based on category/topic
    const category = intelligence.metadata?.category || intelligence.category;
    
    return research.find((r: any) => 
      r.topic.toLowerCase().includes(category?.toLowerCase())
    ) || null;
  }
  
  /**
   * Get processed intelligence ready for writing
   */
  private async getProcessedIntelligence(): Promise<any[]> {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    
    if (!supabaseUrl || !supabaseKey) {
      return [];
    }
    
    try {
      const response = await fetch(
        `${supabaseUrl}/rest/v1/raw_intelligence?processed_by_researcher=eq.true&processed_by_writer=eq.false&order=extracted_at.desc&limit=50`,
        {
          headers: {
            'Authorization': `Bearer ${supabaseKey}`,
            'apikey': supabaseKey,
          },
        }
      );
      
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      
      const allIntelligence = await response.json() as any[];
      
      // Filter out premium targets (airdrop farming accounts) to avoid overlap
      const premiumTargets = ['@bankrbot', '@wallchain_xyz', '@kloutgg'];
      const filteredIntelligence = allIntelligence.filter(item => 
        !premiumTargets.includes(item.source_account)
      );
      
      log.info({ 
        total: allIntelligence.length, 
        filtered: filteredIntelligence.length,
        excluded: allIntelligence.length - filteredIntelligence.length
      }, '[Agent 3] Filtered intelligence for general content generation');
      
      return filteredIntelligence;
    } catch (error) {
      log.error({ error: (error as Error).message }, '[Agent 3] Failed to get processed intelligence');
      return [];
    }
  }
  
  /**
   * Get unused research
   */
  private async getUnusedResearch(): Promise<any[]> {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    
    if (!supabaseUrl || !supabaseKey) {
      return [];
    }
    
    try {
      const response = await fetch(
        `${supabaseUrl}/rest/v1/research_data?used_in_content=eq.false&order=created_at.desc&limit=20`,
        {
          headers: {
            'Authorization': `Bearer ${supabaseKey}`,
            'apikey': supabaseKey,
          },
        }
      );
      
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      
      return await response.json() as any[];
    } catch (error) {
      log.error({ error: (error as Error).message }, '[Agent 3] Failed to get research');
      return [];
    }
  }
  
  /**
   * Store content in queue
   */
  private async storeInQueue(content: any): Promise<void> {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    
    if (!supabaseUrl || !supabaseKey) {
      throw new Error('Supabase not configured');
    }
    
    const response = await fetch(`${supabaseUrl}/rest/v1/content_queue`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${supabaseKey}`,
        'apikey': supabaseKey,
        'Prefer': 'return=minimal'
      },
      body: JSON.stringify(content)
    });
    
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Failed to store in queue: ${response.status} - ${error}`);
    }
  }
  
  /**
   * Mark intelligence as processed by writer
   */
  private async markAsProcessedByWriter(ids: string[]): Promise<void> {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    
    if (!supabaseUrl || !supabaseKey || ids.length === 0) {
      return;
    }
    
    for (const id of ids) {
      try {
        await fetch(`${supabaseUrl}/rest/v1/raw_intelligence?id=eq.${id}`, {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${supabaseKey}`,
            'apikey': supabaseKey,
            'Prefer': 'return=minimal'
          },
          body: JSON.stringify({ processed_by_writer: true })
        });
      } catch (error) {
        log.warn({ id, error: (error as Error).message }, '[Agent 3] Failed to mark as processed');
      }
    }
  }
}

